#!/usr/bin/bash
# Copyright (c) 2019 Lukas Zumvorde
#
# Permission is hereby granted, free of charge, to any person obtaining a 
# copy of this software and associated documentation files (the "Software"), to 
# deal in the Software without restriction, including without limitation 
# the rights to use, copy, modify, merge, publish, distribute, 
# sublicense, and/or sell copies of the Software, and to permit persons to 
# whom the Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in 
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR 
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, 
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE 
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER 
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING 
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER 
# DEALINGS IN THE SOFTWARE. 



batterystatus=$(acpi -b)
charge=$( echo -e "$batterystatus" | awk '{ gsub("%,*","",$4) } { print $4 }' )
loading=$( echo -e "$batterystatus" | awk '{ if($3=="Charging,"||$3=="Unknown,"){print "1"}else{print "0"} }' )
if [ $loading = "1" ]; then
	icon=""
	color="#22DD22"
else
	if [ $charge -ge 88 ]; then
		icon=""
		color="#22DD22"
  elif [ $charge -ge 63 ]; then
		icon=""
		color="#99DD22"
  elif [ $charge -ge 38 ]; then
		icon=""
		color="#DDDD22"
  elif [ $charge -ge 13 ]; then
		icon=""
		color="#DD9922"
	else
		icon=""
		color="#DD2222"
	fi
fi

echo -e "$icon$charge%"
echo -e "$icon$charge%"
echo -e "$color"

