#!/bin/bash
# Copyright (c) 2019 Lukas Zumvorde
#
# Permission is hereby granted, free of charge, to any person obtaining a 
# copy of this software and associated documentation files (the "Software"), to 
# deal in the Software without restriction, including without limitation 
# the rights to use, copy, modify, merge, publish, distribute, 
# sublicense, and/or sell copies of the Software, and to permit persons to 
# whom the Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in 
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR 
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, 
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE 
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER 
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING 
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER 
# DEALINGS IN THE SOFTWARE. 

if [[ $BLOCK_BUTTON ]]; then
	# react to mouse buttons
	if [ "$BLOCK_BUTTON" -eq "1" ]; then 
		mocp --next 
	fi
	if [ "$BLOCK_BUTTON" -eq "3" ]; then
		mocp --previous
	fi
	if [ "$BLOCK_BUTTON" -eq "2" ]; then
		# Check if server is already running
		running=$(ps -e | grep mocp | wc -l)
		if [ "$running" -eq 0 ]; then
			mocp --server
			mocp --play
		else
			mocp --toggle-pause
		fi
	fi
	sleep 0.25
fi

FILENAME=$(mocp --format "%file")
ERROR=$(echo $FILENAME | grep FATAL_ERROR)
if [[ $ERROR ]]; then
	FILENAME="none"
elif [[ $FILENAME ]]; then
	FILENAME=$(basename "$FILENAME")
	FILENAME=${FILENAME%.*}
else
	FILENAME="none"
fi
echo $FILENAME

