#!/usr/bin/bash
# Copyright (c) 2019 Lukas Zumvorde
#
# Permission is hereby granted, free of charge, to any person obtaining a 
# copy of this software and associated documentation files (the "Software"), to 
# deal in the Software without restriction, including without limitation 
# the rights to use, copy, modify, merge, publish, distribute, 
# sublicense, and/or sell copies of the Software, and to permit persons to 
# whom the Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in 
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR 
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, 
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE 
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER 
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING 
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER 
# DEALINGS IN THE SOFTWARE. 

channels="sovietwomble\ncyanideplaysgames\nbattsgo\nivanthecrazy42\nvulkis"

choices=$(echo -e "$channels" | awk '{ printf "%s\t" , $1 ; system("curl -s -H \x27Client-ID: ctf0u38gzxl1emqdrsp17y0e20o1ajh\x27 -X GET \x27https://api.twitch.tv/helix/streams?user_login=" $1 "\x27 | jq \x27.data | .[0] | .title\x27") }' | grep -v -P "\tnull$") 

if [[ -z "$choices" ]]; then
	numstreams="0" 
	echo $numstreams
else
	numstreams=$(echo -e "$choices" | wc -l)
	echo $numstreams
fi

if [[ "$BLOCK_BUTTON" -eq "1" ]]; then
	choice=$(echo -e "$choices" | dmenu -i -l 5 -p "Channel Name")
	channelname=$(echo -e "$choice" | awk -F "\t" '{print $1}')
	if [[ -z "$channelname" ]]; then
		mpv "https://www.twitch.tv/"$channelname
	fi
fi

# curl -s -H 'Client-ID: ctf0u38gzxl1emqdrsp17y0e20o1ajh' -X GET 'https://api.twitch.tv/helix/streams?user_login=cyanideplaysgames' | jq '.data | .[0] | .title'
# curl -s -H 'Client-ID: ctf0u38gzxl1emqdrsp17y0e20o1ajh' -X GET 'https://api.twitch.tv/helix/streams?user_login=cyanideplaysgames' | jq '.data | .[0] | .user_name'





