#!/usr/bin/bash
# Copyright (c) 2019 Lukas Zumvorde
#
# Permission is hereby granted, free of charge, to any person obtaining a 
# copy of this software and associated documentation files (the "Software"), to 
# deal in the Software without restriction, including without limitation 
# the rights to use, copy, modify, merge, publish, distribute, 
# sublicense, and/or sell copies of the Software, and to permit persons to 
# whom the Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in 
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR 
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, 
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE 
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER 
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING 
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER 
# DEALINGS IN THE SOFTWARE. 


if [[ "$BLOCK_BUTTON" -eq "1" ]]; then
	pulseaudio-ctl mute
fi

if [[ "$BLOCK_BUTTON" -eq "3" ]]; then
	pavucontrol
fi

if [[ "$BLOCK_BUTTON" -eq "4" ]]; then
	pulseaudio-ctl up 5
fi

if [[ "$BLOCK_BUTTON" -eq "5" ]]; then
	pulseaudio-ctl down 5
fi

status=$(pulseaudio-ctl full-status)
volume=$(echo -e "$status" | awk '{print $1}')
mutestate=$(echo -e "$status" | awk '{print $2}')

if [ "$mutestate" = "yes" ]; then
	volumeicon=""
else
	volumeicon=""
fi

echo $volumeicon""$volume"%"
